[project]
name = 'project-template'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 3
epoch = 3.0
